### ISSUE TITLE
Cannot set property 'dsl' on null object

### ISSUE THREAD

**Issue by wjq1981** [bschiffthaler/nf-pseudopipe#1]
When I make, I get

- [ ] nextflow run -with-dag pipeline.dot -with-report process_execution.html \
- [ ]   -with-timeline timeline.html -resume main.nf
- [ ] N E X T F L O W  ~  version 19.01.0
- [ ] Launching `main.nf` [berserk_mirzakhani] - revision: 7471aeccbc
- [ ] WARN: It appears you have never run this project before -- Option `-resume` is ignored
- [ ] ERROR ~ Cannot set property 'dsl' on null object
- [ ] 
- [ ]  -- Check script 'main.nf' at line: 1 or see '.nextflow.log' file for more details
- [ ] make: *** [Makefile:6：main]  Error 1

Do you know what causes it?
Rregards.

**Comment by bschiffthaler** [comment]
Hi.

Your version of Nextflow is rather outdated. I would first try to update to v22.

**Comment by wjq1981** [comment]
> Hi.
> 
> Your version of Nextflow is rather outdated. I would first try to update to v22.

Hi, when I updated to v22 as you said, the previous error was solved. But it now has other errors. Is there some script to install?

9月-15 16:37:09.442 [main] DEBUG nextflow.cli.Launcher - $> nextflow run -with-dag pipeline.dot -with-report process_execution.html -with-timeline timeline.html -resume main.nf
9月-15 16:37:09.559 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.5
9月-15 16:37:09.599 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /hdd/data/wangjq/Software/nf-pseudopipe/nextflow.config
9月-15 16:37:09.602 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /hdd/data/wangjq/Software/nf-pseudopipe/nextflow.config
9月-15 16:37:09.649 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
9月-15 16:37:10.889 [main] WARN  nextflow.config.ConfigBuilder - It appears you have never run this project before -- Option `-resume` is ignored
9月-15 16:37:10.905 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
9月-15 16:37:10.922 [main] INFO  nextflow.cli.CmdRun - Launching `main.nf` [deadly_mestorf] DSL2 - revision: 7471aeccbc
9月-15 16:37:10.935 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; plugins-dir=/home/wangjq/.nextflow/plugins; core-plugins: nf-amazon@1.7.2,nf-azure@0.13.2,nf-console@1.0.3,nf-ga4gh@1.0.3,nf-google@1.1.4,nf-sqldb@0.4.0,nf-tower@1.4.0
9月-15 16:37:10.936 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
9月-15 16:37:10.946 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
9月-15 16:37:10.947 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
9月-15 16:37:10.952 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
9月-15 16:37:10.960 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
9月-15 16:37:11.007 [main] DEBUG nextflow.Session - Session uuid: 7d4b37d3-fa40-4996-a583-a470df642d29
9月-15 16:37:11.007 [main] DEBUG nextflow.Session - Run name: deadly_mestorf
9月-15 16:37:11.007 [main] DEBUG nextflow.Session - Executor pool size: 256
9月-15 16:37:11.047 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.04.5 build 5708
  Created: 15-07-2022 16:09 UTC (16-07-2022 00:09 CDT)
  System: Linux 5.15.0-46-generic
  Runtime: Groovy 3.0.10 on OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src
  Encoding: UTF-8 (UTF-8)
  Process: 1586833@ubuntu-desktop [192.168.1.103]
  CPUs: 256 - Mem: 503.7 GB (362.8 GB) - Swap: 50 GB (2.5 MB)
9月-15 16:37:11.079 [main] DEBUG nextflow.Session - Work-dir: /hdd/data/wangjq/Software/nf-pseudopipe/work [ext2/ext3]
9月-15 16:37:11.079 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /hdd/data/wangjq/Software/nf-pseudopipe/bin
9月-15 16:37:11.090 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
9月-15 16:37:11.101 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
9月-15 16:37:11.139 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
9月-15 16:37:11.150 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 257; maxThreads: 1000
9月-15 16:37:11.323 [main] DEBUG nextflow.Session - Session start invoked
9月-15 16:37:12.427 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
9月-15 16:37:12.773 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
9月-15 16:37:12.774 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
9月-15 16:37:12.782 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
9月-15 16:37:12.796 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=256; memory=503.7 GB; capacity=256; pollInterval=100ms; dumpInterval=5m
9月-15 16:37:13.023 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
9月-15 16:37:13.023 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
9月-15 16:37:13.036 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
9月-15 16:37:13.037 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
9月-15 16:37:13.046 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
9月-15 16:37:13.046 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
9月-15 16:37:13.065 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
9月-15 16:37:13.065 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
9月-15 16:37:13.096 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: local
9月-15 16:37:13.097 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
9月-15 16:37:13.128 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: prep_fasta, index_fasta_plus, prep_ppipe_out, pseudopipe, index_fasta, blast_plus, prep_gff, blast
9月-15 16:37:13.129 [main] DEBUG nextflow.Session - Ignite dataflow network (7)
9月-15 16:37:13.134 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > prep_gff
9月-15 16:37:13.135 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > prep_fasta
9月-15 16:37:13.135 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > index_fasta_plus
9月-15 16:37:13.136 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > blast_plus
9月-15 16:37:13.137 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > prep_ppipe_out
9月-15 16:37:13.138 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > pseudopipe
9月-15 16:37:13.140 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
9月-15 16:37:13.141 [main] DEBUG nextflow.Session - Session await
9月-15 16:37:13.163 [Actor Thread 9] DEBUG nextflow.util.CacheHelper - Unable to get file attributes file: /hdd/data/wangjq/Software/nf-pseudopipe/data/test.fasta -- Cause: java.nio.file.NoSuchFileException: /hdd/data/wangjq/Software/nf-pseudopipe/data/test.fasta
9月-15 16:37:13.197 [Actor Thread 9] DEBUG n.splitter.AbstractTextSplitter - Splitter `Fasta` collector path: nextflow.splitter.TextFileCollector$CachePath(/hdd/data/wangjq/Software/nf-pseudopipe/work/3f/67be104e466ef2601b343ded2a440f/split, null)
9月-15 16:37:13.255 [Actor Thread 9] ERROR nextflow.extension.DataflowHelper - @unknown
java.nio.file.NoSuchFileException: /hdd/data/wangjq/Software/nf-pseudopipe/data/test.fasta
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at nextflow.splitter.AbstractSplitter.newInputStream(AbstractSplitter.groovy:454)
	at nextflow.splitter.AbstractTextSplitter.newReader(AbstractTextSplitter.groovy:153)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource0(AbstractTextSplitter.groovy:131)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource(AbstractTextSplitter.groovy:113)
	at nextflow.splitter.AbstractTextSplitter.normalizeSource(AbstractTextSplitter.groovy)
	at nextflow.splitter.AbstractSplitter.apply(AbstractSplitter.groovy:154)
	at nextflow.extension.SplitOp$_applySplittingOperator_closure1.doCall(SplitOp.groovy:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.extension.DataflowHelper$_subscribeImpl_closure2.doCall(DataflowHelper.groovy:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
9月-15 16:37:13.270 [Actor Thread 9] DEBUG nextflow.Session - Session aborted -- Cause: /hdd/data/wangjq/Software/nf-pseudopipe/data/test.fasta
9月-15 16:37:13.334 [Actor Thread 9] DEBUG nextflow.Session - The following nodes are still active:
[process] prep_gff
  status=ACTIVE
  port 0: (value) bound ; channel: script
  port 1: (value) bound ; channel: gff
  port 2: (cntrl) -     ; channel: $

[process] prep_fasta
  status=ACTIVE
  port 0: (value) bound ; channel: script
  port 1: (value) bound ; channel: fasta
  port 2: (cntrl) -     ; channel: $

[process] index_fasta_plus
  status=ACTIVE
  port 0: (value) bound ; channel: fasta_mask
  port 1: (cntrl) -     ; channel: $

[process] blast_plus
  status=ACTIVE
  port 0: (value) bound ; channel: fasta_mask
  port 1: (value) OPEN  ; channel: indexfiles
  port 2: (queue) OPEN  ; channel: split
  port 3: (cntrl) -     ; channel: $

[process] prep_ppipe_out
  status=ACTIVE
  port 0: (value) bound ; channel: script
  port 1: (value) OPEN  ; channel: split
  port 2: (cntrl) -     ; channel: $

[process] pseudopipe
  status=ACTIVE
  port 0: (value) bound ; channel: fasta_mask
  port 1: (value) OPEN  ; channel: indexfiles
  port 2: (value) bound ; channel: fasta_protein
  port 3: (value) OPEN  ; channel: fasta_chr
  port 4: (value) OPEN  ; channel: exlocs
  port 5: (value) OPEN  ; channel: out
  port 6: (cntrl) -     ; channel: $

9月-15 16:37:13.344 [main] DEBUG nextflow.Session - Session await > all process finished
9月-15 16:37:13.345 [main] DEBUG nextflow.Session - Session await > all barriers passed
9月-15 16:37:13.377 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
9月-15 16:37:13.378 [main] DEBUG nextflow.trace.ReportObserver - Flow completing -- rendering html report
9月-15 16:37:13.389 [main] DEBUG nextflow.trace.ReportObserver - Execution report summary data:
  []
9月-15 16:37:13.410 [Actor Thread 23] WARN  nextflow.container.SingularityCache - Singularity cache directory has not been defined -- Remote image will be stored in the path: /hdd/data/wangjq/Software/nf-pseudopipe/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
9月-15 16:37:13.411 [Actor Thread 23] INFO  nextflow.container.SingularityCache - Pulling Singularity image docker://bschiffthaler/python:3.9 [cache /hdd/data/wangjq/Software/nf-pseudopipe/work/singularity/bschiffthaler-python-3.9.img]
9月-15 16:37:13.411 [Actor Thread 24] INFO  nextflow.container.SingularityCache - Pulling Singularity image docker://bschiffthaler/ncbi-blast:2.11.0 [cache /hdd/data/wangjq/Software/nf-pseudopipe/work/singularity/bschiffthaler-ncbi-blast-2.11.0.img]
9月-15 16:37:14.109 [main] DEBUG nextflow.trace.TimelineObserver - Flow completing -- rendering html timeline
9月-15 16:37:14.230 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
9月-15 16:37:14.268 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye

**Comment by bschiffthaler** [comment]
Alright, did you:
  * Run `make` or `make test`?
  * Did you configure the run for your data? By default we assume that you edited `nextflow.config` or that you override the parameters on the command line, e.g.: `nextflow run main.nf --gff <PATH_TO_GFF_FILE> ...`

**Comment by bschiffthaler** [comment]
Note that I'm not recommending you to run `make test`, that is usually for development rather than using the pipeline in production. I recommend that you edit the config file with paths to your data and run the nextflow command itself, don't run the makefile

**Comment by wjq1981** [comment]
> Note that I'm not recommending you to run `make test`, that is usually for development rather than using the pipeline in production. I recommend that you edit the config file with paths to your data and run the nextflow command itself, don't run the makefile

Hi, I tried to run my own file, I replaced 'gff = , fasta_nomask = , fasta_mask = , fasta_protein = ' in the nextflow.config file with all my own files and still with absolute paths, but it still reports an error. As follows:
Error executing process > 'prep_fasta'

Caused by:
  Process `prep_fasta` terminated with an error exit status (1)

Command executed:

  python prep_fasta.py ChrA-n.fasta.masked

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Converting SIF file to temporary sandbox...
  /bin/bash: line 0: cd: /hdd/data/wangjq/Software/nf-pseudopipe1/work/9a/b4560cd56fba66a99a33a7685f83e5: No such file or directory
  /bin/bash: .command.sh: No such file or directory
  INFO:    Cleaning up image...

Work dir:
  /hdd/data/wangjq/Software/nf-pseudopipe1/work/9a/b4560cd56fba66a99a33a7685f83e5

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by bschiffthaler** [comment]
Are you familiar with configuring `nextflow` and `singularity`? To me this looks like the singularity container does not have access to the file path. If you are running on an HPC, make sure that you have mounts configured correctly in singularity, e.g. with something like this in the config

```
singularity {
  enabled = true
  autoMounts = true
}
```
See also [here](https://www.nextflow.io/docs/latest/config.html#config-singularity)

**Comment by wjq1981** [comment]
> 

Thank you very much for your answer, I'm going to learn how to use nextflow and singularity.
